FROM php:7-apache

COPY ./frontend/ /var/www/html
ADD https://developers.braintreepayments.com/client_libraries/php/braintree-php-5.4.0.tgz /var/www/html
WORKDIR /var/www/html 

RUN tar -xzf braintree-php-5.4.0.tgz && mv braintree-php-5.4.0 braintree/ && rm braintree-php-5.4.0.tgz
RUN chown -R www-data:www-data /var/www 

EXPOSE 8082